;; This file of common date formats was copied from
;; https://github.com/clj-time/clj-time/blob/master/src/clj_time/format.clj
(ns shashy.date-utilities.date-formats
  (:import [org.joda.time DateTimeZone]
           [org.joda.time.format DateTimeFormat ISODateTimeFormat]))

(def formats
  (let [local-tz (DateTimeZone/getDefault)]
    (map #(.withZone % local-tz)
         [(ISODateTimeFormat/basicDate)
          (ISODateTimeFormat/basicDateTime)
          (ISODateTimeFormat/basicDateTimeNoMillis)
          (ISODateTimeFormat/basicOrdinalDate)
          (ISODateTimeFormat/basicOrdinalDateTime)
          (ISODateTimeFormat/basicOrdinalDateTimeNoMillis)
          (ISODateTimeFormat/basicTime)
          (ISODateTimeFormat/basicTimeNoMillis)
          (ISODateTimeFormat/basicTTime)
          (ISODateTimeFormat/basicTTimeNoMillis)
          (ISODateTimeFormat/basicWeekDate)
          (ISODateTimeFormat/basicWeekDateTime)
          (ISODateTimeFormat/basicWeekDateTimeNoMillis)
          (ISODateTimeFormat/date)
          (ISODateTimeFormat/dateElementParser)
          (ISODateTimeFormat/dateHour)
          (ISODateTimeFormat/dateHourMinute)
          (ISODateTimeFormat/dateHourMinuteSecond)
          (ISODateTimeFormat/dateHourMinuteSecondFraction)
          (ISODateTimeFormat/dateHourMinuteSecondMillis)
          (ISODateTimeFormat/dateOptionalTimeParser)
          (ISODateTimeFormat/dateParser)
          (ISODateTimeFormat/dateTime)
          (ISODateTimeFormat/dateTimeNoMillis)
          (ISODateTimeFormat/dateTimeParser)
          (ISODateTimeFormat/hour)
          (ISODateTimeFormat/hourMinute)
          (ISODateTimeFormat/hourMinuteSecond)
          (ISODateTimeFormat/hourMinuteSecondFraction)
          (ISODateTimeFormat/hourMinuteSecondMillis)
          (ISODateTimeFormat/localDateOptionalTimeParser)
          (ISODateTimeFormat/localDateParser)
          (ISODateTimeFormat/localTimeParser)
          (ISODateTimeFormat/ordinalDate)
          (ISODateTimeFormat/ordinalDateTime)
          (ISODateTimeFormat/ordinalDateTimeNoMillis)
          (ISODateTimeFormat/time)
          (ISODateTimeFormat/timeElementParser)
          (ISODateTimeFormat/timeNoMillis)
          (ISODateTimeFormat/timeParser)
          (ISODateTimeFormat/tTime)
          (ISODateTimeFormat/tTimeNoMillis)
          (ISODateTimeFormat/weekDate)
          (ISODateTimeFormat/weekDateTime)
          (ISODateTimeFormat/weekDateTimeNoMillis)
          (ISODateTimeFormat/weekyear)
          (ISODateTimeFormat/weekyearWeek)
          (ISODateTimeFormat/weekyearWeekDay)
          (ISODateTimeFormat/year)
          (ISODateTimeFormat/yearMonth)
          (ISODateTimeFormat/yearMonthDay)
          (DateTimeFormat/forPattern "EEE, dd MMM yyyy HH:mm:ss Z")
          (DateTimeFormat/forPattern "yyyy-MM-dd HH:mm:ss")])))
